openapi: 3.0.0
info:
  title: LogiXbackend API
  version: 1.0.0

servers:
  - url: /api

paths:
  /transporter/send-otp:
    $ref: './paths/transporter.yaml#/sendOtp'
  /transporter/verify-otp:
    $ref: './paths/transporter.yaml#/verifyOtp'
  /transporter/register:
    $ref: './paths/transporter.yaml#/registerTransporter'
  /transporter/login:
    $ref: './paths/transporter.yaml#/loginTransporter'
  /form/ftl:
    $ref: './paths/form.yaml#/Ftl'
  /form/packers-movers:
    $ref: './paths/form.yaml#/PackersMovers'
  /form/contact:
    $ref: './paths/form.yaml#/ContactForm'
  /transporter/add-vehicle:
    $ref: './paths/transporter.yaml#/TransporterAddVehicle'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Enter the JWT token obtained after OTP verification.
  schemas:
    FtlRequestSchema:
      $ref: './schemas/ftlRequest.yaml#/FtlRequestSchema'
    SendOtpRequest:
      $ref: './schemas/transporter.schema.yaml#/SendOtpRequest'
    VerifyOtpRequest:
      $ref: './schemas/transporter.schema.yaml#/VerifyOtpRequest'
    UserAlreadyExistsError:
      $ref: './schemas/common.schema.yaml#/UserAlreadyExistsError'
    UnAuthorizedError:
      $ref: './schemas/common.schema.yaml#/UnAuthorizedError'
    InternalServerError:
      $ref: './schemas/common.schema.yaml#/InternalServerError'
    ValidationError:
      $ref: './schemas/common.schema.yaml#/ValidationError'
    PackersAndMovers:
      $ref: './schemas/packersAndMovers.schema.yaml#/PackersAndMovers'
    Vehicle:
      $ref: './schemas/vehicle.schema.yaml#/AddVehicleRequest'